name: Run and Test String Problems Notebook

on:
  push:
    paths:
      - 'String Problems.ipynb'
      - '.github/workflows/python-string-problems.yml'
  pull_request:
    paths:
      - 'String Problems.ipynb'
      - '.github/workflows/python-string-problems.yml'

jobs:
  test-notebook:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert

      - name: Execute and Test Notebook
        run: |
          jupyter nbconvert --to notebook --execute "String Problems.ipynb" --output executed.ipynb --ExecutePreprocessor.timeout=300

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: executed.ipynb